version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8001:8001"
    environment:
      - SPOONACULAR_API_KEY=${SPOONACULAR_API_KEY}
    volumes:
      - ./recipe_app/backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8001 --reload

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true

  # Uncomment this section if you want to use nginx as a reverse proxy
  # nginx:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.nginx
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - frontend
  #     - backend